name: vault

on:
  push:
    branches: [ master ] 


jobs:
    build:
         runs-on: ubuntu-latest 
         steps:
            # ...
            - name: Import Secrets
              uses: hashicorp/vault-action@v2
              with:
                url: http://54.89.147.158:8200
                token: ${{ secrets.VAULT}}
                caCertificate: ${{ secrets.VAULT_CA_CERT }}
                secrets: |
                    secrets/kv/kv accesskey | AWS_ACCESS_KEY_ID ;
                    secret/kv/kv secretkey | AWS_SECRET_ACCESS_KEY ;
                    
            # ...
